# Generated by Django 2.0.6 on 2019-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cityOrOrigin', models.CharField(max_length=30)),
                ('richOrSuperPower', models.CharField(max_length=20)),
                ('whichSuperPower', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('examples', models.TextField()),
            ],
        ),
    ]
